### ISSUE TITLE
Required attribute prevents Invalid Format message

### ISSUE THREAD

**Issue by dmopuri** [alenaksu/mdPickers#104]
https://codepen.io/anon/pen/LNvPVL

If we have required attribute and tried to enter any invalid date then it is always throwing "This is required" error instead of "Invalid Format"

This issue applies for both date and time pickers and this is happening only for "Invalid format" not for min and max errors

**Comment by BenArunski** [comment]
+1

**Comment by dmopuri** [comment]
@alenaksu Thank You for fixing the bug real quick!
