### ISSUE TITLE
$mdpTimePicker  some time watch click is not working.

### ISSUE THREAD

**Issue by sheikhbarkat** [alenaksu/mdPickers#110]
Hi,
I'm implement mdptimepicker in my website, but i am facing issue ,  timepicker sometime is not working,  time between 6 to 3 is not clickable or not drag able, it reset default 6 . it happens sometime.

--------------------------------- Angular ------------------------
    < div style="margin:15px 0px" >
               < label >SET TIME< /label >
                         < div class="form-group" style="height:inherit;margin:0px" >
                            < input   maxlength="50" id="txthours"  ng-value=""  ng-model="txthours"   placeholder="Hours"     type="text" class="form-control  Alram-icon "  ng-click="showTimePicker($event)"  />
                        < /div >
          < /div >

---------------------------- controller ---------------------
$scope.showTimePicker = function (ev)
     {
         $mdpTimePicker($scope.lastTimeSelected, { targetEvent: ev }).then(function (selectedDate) {
             var hours = selectedDate.getHours();
             var minutes = selectedDate.getMinutes();
             var ampm = hours >= 12 ? 'PM' : 'AM';
             hours = hours % 12;
             hours = hours ? hours : 12; // the hour '0' should be '12'
             minutes = minutes < 10 ? '0' + minutes : minutes;
             var strTime = hours + ':' + minutes + ' ' + ampm;
             $scope.txthours = strTime;
             $scope.lastTimeSelected = selectedDate;
         });
     };

**Comment by alenaksu** [comment]
Hi @sheikhbarkat, can you provide a codepen of the issue?

**Comment by rajeshsricharan** [comment]
Hi @alenaksu ,
I'm also facing the same issue.
![mdptp](https://cloud.githubusercontent.com/assets/15145745/15573895/cd5c5dce-2367-11e6-94c9-279a20716aca.gif)

**Comment by alenaksu** [comment]
Hi @rajeshsricharan, can you provide a codepen of the issue?

**Comment by rajeshsricharan** [comment]
Hi @alenaksu , Its working in codepen but its not working in my project. 
I'm thinking the issue is with the versions of momentjs and angular-material.
can you please suggest me the required versions ?

**Comment by rajeshsricharan** [comment]
@alenaksu Angular messages was missing in my project. Installed messages and everything works fine now. Thanks for your time.

@sheikhbarkat can you please check whether all the dependencies are installed correctly? Thanks.

**Comment by sheikhbarkat** [comment]
How to install Angular messages?

**Comment by ashishyadav23** [comment]
@sheikhbarkat bower/npm install angular-messages
