### ISSUE TITLE
Linked datepickers

### ISSUE THREAD

**Issue by rcevs** [alenaksu/mdPickers#117]
Hi. I was wondering if there's a way to update a second picker when you select a date. Specifically I need to set a second datepicker exactly a year after the value of the first one. Thanks a lot!

**Comment by gabrieldevelops** [comment]
One solution that can be added to a new version:

In CalendarCtrl :
-  create new variable:
     self.displayFormat = $scope.$parent.datepicker.displayFormat;
- in method this.isDayEnabled, switch to:
      this.isDayEnabled = function (day) {
         var minDate = this.minDate ? moment(this.minDate.format(self.displayFormat), self.displayFormat, true) : this.minDate;
         var maxDate = this.maxDate ? moment(this.maxDate.format(self.displayFormat), self.displayFormat, true) : this.maxDate;
         day = moment(moment(day).format(self.displayFormat), self.displayFormat, true);
         return (!minDate || minDate.toDate() <= day.toDate()) &&
          (!maxDate || maxDate.toDate() >= day.toDate()) &&
          (!self.dateFilter || !self.dateFilter(day));
  };

Tested and working
Obs: English translator google

**Comment by rcevs** [comment]
Hi Gabriel. I just tried your solution, but it wasn't quite what I was looking for. Thanks anyway!

**Comment by alenaksu** [comment]
Hi @rcevs, you can do it using the $mdpDatePicker service.

``` js
$mdpDatePicker(date).then(function(selectedDate) {
  var yearPlusOne = moment(selectedDate).add(1, 'year').toDate();
  $mdpDatePicker(yearPlusOne).then(function(selectedDate) {

  });
});
```

**Comment by rcevs** [comment]
Thanks @alenaksu! Your solution works fine. Unfortunately I would prefer not to trigger the second date picker and update the field automatically (without the need of the user's intervention). 

I tried assigning the yearPlusOne variable directly to the second date model but this doesn't update the field's $viewValue nor the $valid property, and as the field is "required", it doesn't allow the form submission until I touch the second datepicker. Any idea?

**Comment by alenaksu** [comment]
@rcevs Can you please provide a codepen of the issue?
