### ISSUE TITLE
Another way to open datepicker

### ISSUE THREAD

**Issue by edimitchel** [alenaksu/mdPickers#12]
Hello,
can you make that pickers can be open on focus of a input ? I know I can do it with `ng-focus="openPicker()"` but the problem is that when I select date, the picker opens again (triggered by focus on input)..

Hope that you will fix/upgrade my suggestion.

**Comment by alenaksu** [comment]
Hi,
did you try the mdDatePicker directive?

```html
<input type="text" md-date-picker ng-model="theDate" />
```
