### ISSUE TITLE
Formatting date to DD/MM/YYYY

### ISSUE THREAD

**Issue by dcoferraz** [alenaksu/mdPickers#14]
How could I show this date format in my `<input type="date"> </input>`?

**Comment by alenaksu** [comment]
As far as I know, there is no way to change the format of the HTML5 date input. It depends on browser selected language.

**Comment by dcoferraz** [comment]
Yeah... Indeed @alenaksu, `<input type="date"> </input>` needs a date on ISO format.

The workaround that I had to use was formatting the date with moment.js and setting it to a `<input type="text"> </input>`.

Wouldn't this be a good feature to implement? The formatting of dates in any format?

Thinking of something like this: http://momentjs.com/
