### ISSUE TITLE
Previous and next month buttons not painted correctly.

### ISSUE THREAD

**Issue by swavekl** [alenaksu/mdPickers#18]
Hi I just switched to using your date picker and it works nicely except for the prev/next buttons.  They show as CHE. I assume the component can't locate the chevron left and right icons.  I am using the angular-material-icons component which defines the icons as SVG paths.

Should I be loading these two icons separately?

Also if you could specify the format of the text which shows the date in the input field that would be great e.g. Sunday, January 17, 2016.

**Comment by alenaksu** [comment]
Hi, did you try to follow these instructions? http://google.github.io/material-design-icons/#icon-font-for-the-web
What you have to do is to include the offical Material Icons web font.  

The date format is restricted to browser default format. I think you can easly work around this using the $mdDatePicker service with an input text field.

**Comment by swavekl** [comment]
No I wasn't aware of this font.  I only followed your instructions from the Git code page.  I included the icons font like this and it worked.

<link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet"></head>

Thank you.
