### ISSUE TITLE
Numbers on clock face and AM/PM options not appearing in dialog

### ISSUE THREAD

**Issue by ericodes** [alenaksu/mdPickers#194]
hey @dpoetzsch!

I'm using your fork, thanks for creating that.

I'm seeing something odd, where the clock doesn't fully appear.
![image](https://cloud.githubusercontent.com/assets/7111535/26424511/4bedc420-4086-11e7-8c00-7b4141218bd7.png)

Took a quick look in Dev Tools, and looks like `clock.steps` isn't defined.
![image](https://cloud.githubusercontent.com/assets/7111535/26424532/62023b92-4086-11e7-829e-54ca7575cf04.png)

Was wondering if anyone else have having this issue? Removed and installed it a couple times just to check.

Thank you for your help!

**Comment by ericodes** [comment]
Nevermind, resolved it!

Was because I had chosen an older (1.4) Angular version with Bower resolutions. `clock.steps` were getting defined in an`this.$onInit` which is from Angular 1.6, so just had to change the resolution.

**Comment by dpoetzsch** [comment]
Happy to hear your issue has been resolved. For the future: If you have an issue with the fork it might be better to open the issue there. We'll probably lose track of the states otherwise

**Comment by LoganDupont** [comment]
@dpoetzsch Is it normal that we can't find the issue page on a fork?

**Comment by ericodes** [comment]
Definitely @dpoetzsch! Are you able to turn on the Issues page for your fork? I wasn't able to see the issues tab either. Thanks again for maintaining it!

![screen shot 2017-05-26 at 4 06 58 pm](https://cloud.githubusercontent.com/assets/7111535/26515210/5e4b9f72-422d-11e7-8e10-763543f1517d.png)
![screen shot 2017-05-26 at 4 06 49 pm](https://cloud.githubusercontent.com/assets/7111535/26515213/62c1ead4-422d-11e7-98c7-3922483a49af.png)

**Comment by dpoetzsch** [comment]
Thanks for pointing that out @LoganDupont @ericodes I needed to enable issues on the fork for some reason. Should be working now :)
