### ISSUE TITLE
IE version

### ISSUE THREAD

**Issue by Nathalielim** [alenaksu/mdPickers#21]
Hi,
The code works in Chrome, but not in IE9. Which IE version is supported?

**Comment by alenaksu** [comment]
From Angular Material README:
> Please note that using Angular Material requires the use of Angular 1.3.x or higher. 
> Angular Material is targeted for all browsers with versions n-1; where n is the current browser version.

Current version is IE11, so I think it works well IE11 and IE10, not IE9.
