### ISSUE TITLE
Wrong day

### ISSUE THREAD

**Issue by simonered** [alenaksu/mdPickers#23]
The date is one day earlier than selected

**Comment by alenaksu** [comment]
Can you replicate the issue on codepen, jsfiddle or elsewhere?

**Comment by simonered** [comment]
[Here] (http://codepen.io/simonered/pen/GoOQmY) it is.

**Comment by alenaksu** [comment]
If you display the date in iso format, it will be displayed with the current timezone.
For instance, if your timezone is -0100, you will see something like 2016-01-18T**23**:00:00.000Z.

What day the __getDate__ method returns?

**Comment by simonered** [comment]
You're absolutely right...my mistake.
