### ISSUE TITLE
Styling issues

### ISSUE THREAD

**Issue by soniram** [alenaksu/mdPickers#24]
Hi and thanks for sharing your beautiful calendar !
As you can see, without any modifications, the styling has a lot of minor glitches compared to the demos (year and day names are too small, dates have an oval background,.. ). Any idea of what I'm doing wrong or missing ?

![image](https://cloud.githubusercontent.com/assets/12727585/12653042/56ceee84-c5f6-11e5-94cf-aa0c5a231751.png)

**Comment by alenaksu** [comment]
Hi!
First of all, I guess you forgot to include the [material icon font](https://google.github.io/material-design-icons/#icon-font-for-the-web) and that's why you don't see the next and prev buttons.

Can you tell me what version of Angular Material are you using? 
I had a similar issue in the past that was resolved upgrading Angular Material dependency.

**Comment by soniram** [comment]
Thanks for replying :)
- I know about the missing material icon font, that's why I didn't mention it.
- The screenshot was taken with version 1.0.1
- I tested it with the current version (1.0.4) with no lack

**Comment by alenaksu** [comment]
Can you recreate the issue on Codepen?

**Comment by soniram** [comment]
Very difficult. I'm using an angular material theme named triangular that is huge and copyrighted, not to mention that I have no experience with Codepen (but this is not real problem..). Is there any simple example of yours, on github that could be used for guiding ?

**Comment by alenaksu** [comment]
I'm sorry, I don't have any example on github. The only one is the demo on Codepen.
In which order are you referenced the styles? 
I'm pretty sure that if you put Angular Material before mdPickers this could generate the issue.

**Comment by soniram** [comment]
I'm most sure that this is the case. I'll check it and post back.
Thanks for your help !!!

**Comment by soniram** [comment]
In my case, placing mdPickers css last, fixed dates oval appearance.
It's css conflict for sure. :)
I think that I have to start css overrides. Any directions based on the attached screenshot are welcomed :)
Thanks, once more, for your concern and help

**Comment by alenaksu** [comment]
You're welcome :)

**Comment by Laazarus** [comment]
Hello there ,

Thanks for your directive that i find amazing, I have a similar problem with the style but only for the date picker (not for the time picker). My problem is that when the pop up of the date picker get visible at the beginning the button OK and Cancel do not appear immediately but just after a couple of seconds and when they do they push all the content up cutting off the Month and the left and right arrow like in the image
![image](https://cloud.githubusercontent.com/assets/5720026/16786943/e0a0516e-4898-11e6-944c-601e7282d302.png)

I have checked the order of the styles and it is correct... Any idea of what i am doing wrong? Using the same browser i can see your demo perfectly, 

Thanks again 
Best Regards
