### ISSUE TITLE
TimePicker -- Add ability to drag minute hand

### ISSUE THREAD

**Issue by holly-weisser** [alenaksu/mdPickers#27]
Currently, you have to click where you want the minute hand to go, which makes any minute that doesn't correspond to a number on the clock face a bit harder to get to.

**Comment by alenaksu** [comment]
Hi, this function is already implemented, try to drage the line

**Comment by holly-weisser** [comment]
I would think the drag handle would be the larger dot at the end of the minute hand, rather than the slim line.

**Comment by alenaksu** [comment]
Improved on new release

**Comment by holly-weisser** [comment]
Looks/works great, thank you so much!
