### ISSUE TITLE
Enhancement: dynamic year selector

### ISSUE THREAD

**Issue by JuanELo-O** [alenaksu/mdPickers#3]
Hi!

I need define a year before 1970, but I can see that in the array of years it's defined since 1970.

Thanks! :)

**Comment by alenaksu** [comment]
Hi, I have changed the year range, now it starts from 1900.

A better implementation of the selector will come as soon as the next version of Angular Material will be released.

**Comment by JuanELo-O** [comment]
Ok, thanks for your time :)
