### ISSUE TITLE
Combining Date Picker with Time Picker

### ISSUE THREAD

**Issue by piyushchauhan2011** [alenaksu/mdPickers#34]
I think that we can combine date picker with time picker and can have the time fields below the date fields on left hand side in date picker and change the view to time picker view one when someone clicks on those fields. @alenaksu 

Let me know about the idea :sunglasses:

**Comment by alenaksu** [comment]
Hi, 
according to [Material Design Specs](https://www.google.com/design/spec/components/dialogs.html#dialogs-confirmation-dialogs), should remain focused on a single value.

> Confirmation dialogs can use layouts other than lists, such as a date picker, but remain focused on specifying a single value (picking the date, but not picking the time and date).
