### ISSUE TITLE
Would it be possible to make the time picker work with input type time?

### ISSUE THREAD

**Issue by rvarbanov** [alenaksu/mdPickers#35]
I would like to be able to use your time picker with an input time filed. Just like you have the date on the demo.

**Comment by leocaseiro** [comment]
@rvarbanov it works fine with a time input. I added it to the CodePen demo and you'll see it works just fine:

```html
<md-input-container>
    <label>Time</label>
    <input type="time" ng-click="showTimePicker($event)" ng-model="currentDate" />
</md-input-container>
```

http://codepen.io/anon/pen/jWoVdp

**Comment by alenaksu** [comment]
@rvarbanov @leocaseiro 
There's a directive for that, but I forgot to add it to the demo :)

Here is an example:
```html
<md-input-container>
    <label>Time</label>
    <input type="time" mdp-time-picker ng-model="currentDate" />
</md-input-container>
```

**Comment by rvarbanov** [comment]
Awesome!

The Angular Material folks should just merge your picker in their code :smiley:
