### ISSUE TITLE
Customize Datepicker Icons

### ISSUE THREAD

**Issue by eduardmartinez** [alenaksu/mdPickers#36]
Hi. First at all, thank you so much for the job you have done with this package. It has been really useful to me. I'm working in a project using font-awesome icons pack and we don't want to add another pack, so, is there a way to customize DatePicker's icons?

Thanks in advance. :D

**Comment by alenaksu** [comment]
Material Design Icons dependency will be removed in the next release (#37)

**Comment by eduardmartinez** [comment]
Thanks. I'll wait for next realease then :D
