### ISSUE TITLE
Open mdPickers in md-dialog

### ISSUE THREAD

**Issue by KelvinOm** [alenaksu/mdPickers#38]
Hi.

How open picker in dialog window without close it?

**Comment by Asoseil** [comment]
+1

**Comment by alenaksu** [comment]
Unfortunately multiple dialogs at time cannot be opened.
Afaik, Material specs for the pickers are Android focused.

Meanwhile I'll look for a solution, any suggestion would be appreciate :)

**Comment by rvarbanov** [comment]
+1

**Comment by KelvinOm** [comment]
I know about specs, but datepicker not a dialog:)
What about del «md-dialog» and use something like in Angular Material «md-datepicker-calendar-pane». But u need add show behavior for new block.

**Comment by Asoseil** [comment]
https://github.com/angular/material/issues/698#issuecomment-89858717

**Comment by KelvinOm** [comment]
not best usability solution...

**Comment by alenaksu** [comment]
I've digged a bit into the "Angular Material" source code. There's an undocumented option for $mdDialog, "skipHide". If you set it to True, the mdDialog service doesn't close other dialogs.

But there's an issue when cancelling a dialog [#6912](https://github.com/angular/material/issues/6912)

I think it will work without any problem after Angular Material team will release version 1.0.6.

**Comment by alenaksu** [comment]
[Here](http://codepen.io/alenaksu/pen/wGGPVZ) is a demo of what I was talking about

**Comment by KelvinOm** [comment]
thx i try it and we already use 1.0.6 version:)

I found two problems with this approach:
1) Cancel and clickOutsideToClose close first md-dialog...
2) How i can set skipHide for DatePicker md-dialog?

**Comment by alenaksu** [comment]
As I can see [here](https://github.com/angular/material/releases), current release is 1.0.5

For the issue you mentioned, it's exactly what I was talking about. It was fixed with commit [6d39c21](https://github.com/angular/material/commit/6d39c218a9a4814e12d49d55c55a54d71efaa0d5), but didn't released yet.

**Comment by KelvinOm** [comment]
I get 1.0.6 from cdn
http://cdnjs.cloudflare.com/ajax/libs/angular-material/1.0.6/angular-material.min.js
In this fix bug whit md-errors-spacer, critical for me.

thx for great picker! Really looking forward to the next version:)

**Comment by rvarbanov** [comment]
What is the status of this issue? What are the plans of making the datepicker working in a dialog?

**Comment by alenaksu** [comment]
@rvarbanov done in version 0.7.0, but require angular material  >=1.1-rc1

**Comment by rvarbanov** [comment]
@alenaksu it still looks like you are using md-dialog for the datepicker. Are you considering removing the md-dialog?

**Comment by alenaksu** [comment]
@rvarbanov yes it still using md-dialog, but it shouldn't closes others anymore. I considered to switch away from md-dialog, but maybe later, when everything will work "quite well" :)

**Comment by rvarbanov** [comment]
http://codepen.io/radi/pen/wGzZKx

When you open a datepicker in a dialog it opens under the first dialog. Please see the codepen.

**Comment by alenaksu** [comment]
@rvarbanov make a try without specify the parent option in the dialog

**Comment by rvarbanov** [comment]
@alenaksu I am not sure I understand. Would you please elaborate?

**Comment by alenaksu** [comment]
Look at this http://codepen.io/alenaksu/pen/NNRQrE

**Comment by alenaksu** [comment]
@rvarbanov 
Look at this http://codepen.io/alenaksu/pen/NNRQrE

**Comment by rvarbanov** [comment]
That worked.

BTW I just noticed that on smaller screens < 599px in the calendar the dates are misaligned with the week days.

<img width="521" alt="screen shot 2016-03-14 at 1 32 15 pm" src="https://cloud.githubusercontent.com/assets/2780282/13753413/36c9c674-e9e9-11e5-9f78-e6fdfacf7e67.png">

It looks like a simple CSS fix should resolve that issue. 
Let me know if you need to create a new issue just for that?

**Comment by alenaksu** [comment]
@rvarbanov 
Ouch! Yes please, create a new issue so I'll remember to fix it :D

**Comment by rvarbanov** [comment]
All set!

**Comment by dehart** [comment]
@rvarbanov 

Angular has changed, skipHide to "multiple"

See here: https://github.com/angular/material/issues/10076

**Comment by jimwilde** [comment]
@alenaksu 
I updated my version to use 'multiple' instead of 'skipHide' and it's working.  Would be good for you to update so this doesn't get overwritten if I have to reinstall my npm dependencies.

**Comment by ghost** [comment]
@alenaksu

I updated my version to use 'multiple' instead of 'skipHide' and it's not working.. using angular material 1.1.2...please check the attached codepen...we are in production now and it is causing trouble to lot of users please tell the fix to it

http://codepen.io/Prajwal_Jagadish/pen/ygZodj

**Comment by dandanknight** [comment]
@Prajwal8 I've had the same issue. The `multiple` field needs to be in the mdPickers code itself. I previously forked this project to add `skipHide` and fix a validator issue. I've since updated it to use `multiple` instead of skipHide. It works fine for me. 

You can find it here...

https://github.com/dandanknight/mdPickers.git#master
