### ISSUE TITLE
Clock hands and selector not showing

### ISSUE THREAD

**Issue by dragondgold** [alenaksu/mdPickers#39]
I started using mdPickers. I've all the required dependencies, `moment`, `AngularJS`, `Angular Material` and `Material Design Icons`. But when using the time picker I can't see the clock's hands and the small circle that selects the number in the clock when clicked. 

I tried it in Chrome 48, Microsoft Edge 25 and Internet Explorer 11. On Edge and Explorer I can see the clock's hands but not the circle that selects the number (also on Internet Explorer the hand is offset from where I click).

This is the simple code I'm using:

```
 <md-input-container class="col-md-2 col-md-offset-5">
       <label>Time</label>
       <input type="time" mdp-time-picker ng-model="currentDate" />
 </md-input-container>
```

![image](https://cloud.githubusercontent.com/assets/2932540/13536119/e4ac22ac-e21c-11e5-8496-ac82b64ba571.png)

**Comment by alenaksu** [comment]
Hi, can you replicate the issue on codepen?

**Comment by alenaksu** [comment]
Close due inactivity
