### ISSUE TITLE
FF and Safari timepicker input issue

### ISSUE THREAD

**Issue by rvarbanov** [alenaksu/mdPickers#40]
After selecting the time with the timepicker in Firefox and Safari the input looks like this:
<img width="253" alt="screen shot 2016-03-07 at 2 58 27 pm" src="https://cloud.githubusercontent.com/assets/2780282/13581480/19bfce94-e475-11e5-8894-aa6815fb3ab5.png">

Compared to this in Chrome:
<img width="234" alt="screen shot 2016-03-07 at 2 55 38 pm" src="https://cloud.githubusercontent.com/assets/2780282/13581401/b1eaab40-e474-11e5-925b-2937bb43895b.png">

It would be greater if we could have one unified look across all browsers.

**Comment by alenaksu** [comment]
Hi, afaik each browser shows it differently. 
By the way, in the new version (0.6.0) has been added the ability to specify the format for input[type=text]

Let me know if this feature is what you're looking for
