### ISSUE TITLE
Feat. : Customize first day of the week

### ISSUE THREAD

**Issue by corentin-gautier** [alenaksu/mdPickers#44]
Add an option to set the first day of the week to something else than sunday

**Comment by alenaksu** [comment]
Hi, 
this should depends on the locale used in moment.js
Have you tried to change it?

**Comment by corentin-gautier** [comment]
Nope, because you use moment.weekdaysmin which is just the translation of the days ( so it always start on sunday )

**Comment by alenaksu** [comment]
You're absolutly right! I'll fix it in the next release
