### ISSUE TITLE
Min/Max date doesn't works in Firefox - Error: self.date is undefined

### ISSUE THREAD

**Issue by diana2201** [alenaksu/mdPickers#47]
When I open the example in CodePen in Opera, it works perfectly, but in Mozilla it seems that doesn't work. 
Also when I use the dist in my code, it throws me an error "Error: self.date is undefined", I tried to fix it, adding to mdPickers.js in CalendarCtrl "self.date = moment();", and apparently works, but when I try to change the year, the calendar doesn't show me the correct dates. I attach the error and the calendars.

![error](https://cloud.githubusercontent.com/assets/9339625/13673940/6962f92c-e6a9-11e5-90b9-d936cc1295b1.PNG)

![calendar](https://cloud.githubusercontent.com/assets/9339625/13673939/6961e06e-e6a9-11e5-99f0-af39bbd507db.PNG)

![calendar2](https://cloud.githubusercontent.com/assets/9339625/13673941/69636d08-e6a9-11e5-9e52-572ba8deae81.PNG)

**Comment by alenaksu** [comment]
Hi 
can you create codepen of the issue and tell me which version of Firefox?

**Comment by diana2201** [comment]
Hi,
I'm using the version 45. The error can't be reproduced, in CodePen works, but also I tried use the cdn in my code and I get the error, but now is: 

For Firefox:
![captura](https://cloud.githubusercontent.com/assets/9339625/13678940/5267b0f8-e6bf-11e5-9e6a-bc89c804e453.PNG)

For Opera - Chrome
![captura](https://cloud.githubusercontent.com/assets/9339625/13679033/b24b8ef4-e6bf-11e5-9a73-5ad945977bef.PNG)

You can see that apparently the error is in mdPickers.js file, but I don't know what could be.

**Comment by alenaksu** [comment]
What version of AngularJS are you using?
Without a pen demonstrating the issue is quite hard

**Comment by jfreak** [comment]
Had a similar issue with this...updating angular to the latest version resolved it .

**Comment by alenaksu** [comment]
I think the issue could be related to the **bindToController** property introduced with version 1.4

**Comment by alenaksu** [comment]
@diana2201 news?

**Comment by diana2201** [comment]
Sorry, I had to leave the project for a while, but now I try to use it works great, just update the angular version.
Thanks a lot.

**Comment by ankita120892** [comment]
I have the exactly same problem. Updated the angular version to 1.5.7. Still getting the same error. Please help.

**Comment by alenaksu** [comment]
@ankita120892 Can you replicate the issue on codepen?

**Comment by ankita120892** [comment]
![image](https://cloud.githubusercontent.com/assets/20168056/16386825/c65550f6-3caf-11e6-8cfe-2510001f3d3a.png)

**Comment by alenaksu** [comment]
@ankita120892 I'm sorry but without a codepen I can't figure out where the problem is.
