### ISSUE TITLE
Why no more 'onclick'?

### ISSUE THREAD

**Issue by simonered** [alenaksu/mdPickers#55]
Why pickers don't show anymore at click on input elements?

**Comment by alenaksu** [comment]
@simonered directive now have a template, check che changelog and the demo for more details

**Comment by simonered** [comment]
Yes, I saw....but why do you fire _ng-click_ on icon and not also at input level?

**Comment by alenaksu** [comment]
Because in some case some people would prefer to have the ability to insert the value by hand. 
I can add it as an option for fit your requirements

**Comment by simonered** [comment]
Yes, it could be useful. Thank you.

**Comment by alenaksu** [comment]
@simonered 
if `mdp-open-on-focus`is set, the dialog will open when the input gets focus.
