### ISSUE TITLE
Optional md-no-float and icon

### ISSUE THREAD

**Issue by simonered** [alenaksu/mdPickers#56]
_md-no-float_ and icon should be configurable.

**Comment by alenaksu** [comment]
`mdp-no-float` will do the job

**Comment by simonered** [comment]
I assume `mdp-no-float` will enable/disable label floating....but what about showing/hiding the icon?

**Comment by alenaksu** [comment]
@simonered if you want to hide the icon you can bind the directive as attribute
```javascript
<input name="myname" ng-model="myDate" mdp-date-picker />
```

This will open the picker when the input is clicked

**Comment by simonered** [comment]
Cool! Thank you.

**Comment by gabigeo** [comment]
When using it as attribute format does not work.
For example:
mdp-format="DD.MM.YYYY"

In code I see there are two directives, one for element and one for attribute. But only the one for element is using dateFormat.
