### ISSUE TITLE
Date picker input value does not update after clearing out

### ISSUE THREAD

**Issue by vyrak** [alenaksu/mdPickers#61]
First off, thanks for the awesome pickers.

When I initially select a date, I see the selected date display on the input. When I pick another date, it updates just fine. The problem is after I clear out the date in the input and then try to select a new date, the value stays empty in the input (though the underlying model it's bound to updates).

http://codepen.io/anon/pen/zqoLWe

Additional note, the time picker seems to still be working fine after clearing out the time.

**Comment by alenaksu** [comment]
@vyrak Thank you, I'll fix it in the next release
