### ISSUE TITLE
Deprecation warning: moment construction falls back to js Date.

### ISSUE THREAD

**Issue by gigablox** [alenaksu/mdPickers#66]
`min` and `max` both accept string types when they should accept Date type per material spec.

This also appears to be causing some issues with Moment.JS as you can see from the console in your CodePen example.

**Comment by alenaksu** [comment]
@gigablox The issue you mentioned with moment.js it's just a deprecation warning, resolved in version 0.7.2.

Min and Max will be set up as two-way binding.

**Comment by gigablox** [comment]
Awesome, yea the min max is currently broken in your example, but I'm glad you're aware of it. Looking forward to 7.2! Great work on this btw.
