### ISSUE TITLE
mdp-placeholder not work

### ISSUE THREAD

**Issue by KelvinOm** [alenaksu/mdPickers#67]
Hi, once more.

mdp-placeholder doesn't work anymore with type="date" and after load in place of placeholder we see dd.mm.yyyy.

I try fix this and hope it will be useful for u.

I change code like this:
`'<md-input-container class="md-block">' +`
`    '<label>{{ placeholder }}</label>' +`
`    '<input type="{{ type }}" ng-value="getValue()" aria-label="{{ placeholder }}" />' +`
`'</md-input-container>' `

It work well.

**Comment by alenaksu** [comment]
`mdp-no-float` will do the job
