### ISSUE TITLE
Install a different version of angular! 

### ISSUE THREAD

**Issue by tramonex-dbardaji** [alenaksu/mdPickers#7]
All time I'm doing bower install is adding me an other angular link! 
I think it's because you wrote in dependencies "angularjs" instead "angular".

Can you confirm this? Thanks

**Comment by tramonex-dbardaji** [comment]
Yes, I change the name and it's working properly.

**Comment by alenaksu** [comment]
Yes, I confirm. 
I've just replaced it with the correct dependency.

Let me know if it's ok now
