### ISSUE TITLE
Min Max date in $mdpDatePicker service

### ISSUE THREAD

**Issue by jfreak** [alenaksu/mdPickers#70]
Not able to  set min max date...It always takes the current date!

**Comment by alenaksu** [comment]
@jfreak can you please provide a codepen of the issue?

**Comment by jfreak** [comment]
http://codepen.io/jfreak/pen/jqBdyR

**Comment by alenaksu** [comment]
I think you are confusing the service and the directive.. 
If you want to use the service, here's the correct syntax
```javascript
$mdpDatePicker($scope.currentDate, {
    minDate: minDate, 
    maxDate: maxDate,
    dateFilter: dateFilter,
    targetEvent: ev
}).then(function(selectedDate) {
    $scope.currentDate = selectedDate;
});;
```
*minDate* and *maxDate* if set, can be either a iso date string or a date object
*dateFilter* if set, should be a function

**Comment by jfreak** [comment]
Thanks, It worked..
