### ISSUE TITLE
Cancelling mdPickers from  inside an Angular-material modal closes the modal and not the picker

### ISSUE THREAD

**Issue by DomClaxton** [alenaksu/mdPickers#72]
If I  use mdPickers inside an angular-material modal and trigger the date picker to open, then close the picker it will close the modal underneath first. I must click 'Cancel' a second time in order to close the picker.
This is not very usable if I'm entering a lot of dates inside the modal because each time I need to cancel a date-picker it will close the underlying modal which I will then have to open again.
I suggest it is a scope issue because mdPickers is essentially a modal which  is being called inside of a modal.

**Comment by alenaksu** [comment]
Hi, take a look at this codepen and tell me if it helpshttp://codepen.io/alenaksu/pen/NNRQrE

**Comment by alenaksu** [comment]
@DomClaxton any news about the issue?

**Comment by alenaksu** [comment]
I close the issue. Feel free to reopen if you need support
