### ISSUE TITLE
Error property 'hours' of undefined in angular 1.4.5 and material 0.11.1

### ISSUE THREAD

**Issue by patapron** [alenaksu/mdPickers#74]
Hi
Sorry for my english.
I've a project with angularJS 1.4.5 , angular-material 0.11.1 and the latest library of momentjs and mdPickers. Durin the installation, I selected the appropiate config.

I injectected     "ngMaterial",  "ngAnimate", "ngAria", "ngMessages", "mdPickers" in my module,
'$scope', '$mdpDatePicker', '$mdpTimePicker' in my controller and mdPicker css and js in my template.

My problem happens when I'm push in the icon to define a new hour. 
TypeError: Cannot read property 'hours' of undefined
```
angular.js:12416 TypeError: Cannot read property 'hours' of undefined
    at ClockCtrl.$scope.init (mdPickers.js:684)
    at new ClockCtrl (mdPickers.js:698)
    at Object.invoke (angular.js:4473)
    at extend.instance (angular.js:9093)
    at nodeLinkFn (angular.js:8205)
    at compositeLinkFn (angular.js:7637)
    at publicLinkFn (angular.js:7512)
    at boundTranscludeFn (angular.js:7656)
    at Object.controllersBoundTransclude [as transclude] (angular.js:8273)
    at angular.js:27839
```

I can watch how this = ClockCtrl {} instead of  ClockCtrl {type: "hours", time: n, autoSwitch: true} when arrive to ClockCtrl definition. 

Someone knows what may be the solution?

Thanks.

**Comment by alenaksu** [comment]
@patapron 
Hi, 
can you make a try upgrading to Angular 1.4.9?

**Comment by quentinber** [comment]
If someone else has the problem:
the time picker actually does not work with angular v 1.6.
try downgrading to 1.5 (stable) version to make it works ;)

**Comment by chris0203** [comment]
there was missing a moment object in src.

> function ClockCtrl($scope) {
    var TYPE_HOURS = "hours";
    var TYPE_MINUTES = "minutes";
    var self = this;    
    this.STEP_DEG = 360 / 12;
    this.steps = [];
    this.time = moment(); //missing this line

......

after adding this line this.time = moment(); , everything is fine

**Comment by Celadora** [comment]
To improve upon @chris0203's answer, if you use:
`
this.time = moment($scope.timepicker.time);
`
then the clock hands are not reset back to the current time whenever the dialog is shown
