### ISSUE TITLE
Support use of date picker in mdDialog

### ISSUE THREAD

**Issue by alphazhe** [alenaksu/mdPickers#78]
When I used mdp-date-picker in md-dialog then after clicking cancel button of date picker it closes dialog not date picker. Same thing happens when hit escape button.

**Comment by alenaksu** [comment]
Hi,
it happens of you set parent property in your dialog.
look this pen and tell me if it helps http://codepen.io/alenaksu/pen/NNRQrE

**Comment by shawmanz32na** [comment]
I'm having this issue, except also in the `mdp-time-picker`. I have not set the parent property on my dialog.

I was able to resolve the issue in the `mdp-date-picker` by setting the `clickOutsideToClose` property to false., but this had no effect on the mdp-time-picker.

Any ideas?

**Comment by shawmanz32na** [comment]
I was previously running on angular 1.4.8 and angular-material 1.0.6, but updated to angular 1.4.10 and angular-material 1.0.7, and all seems to be well. That little factoid may come in handy?

**Comment by alphazhe** [comment]
@alenaksu  Thanks that helped...:).
@shawmanz32na In my case its working for both date picker and time picker even if `clickOutsideToClose` property is true.

**Comment by alenaksu** [comment]
@alphazhe @shawmanz32na there was a bug in angular material resolved with commit [6d39c21](https://github.com/angular/material/commit/6d39c218a9a4814e12d49d55c55a54d71efaa0d5)
If I remember correctly it was released after 1.0.6.

**Comment by alphazhe** [comment]
Yes, I was using 1.0.6 before and after updating to latest 1.0.7 it worked.
@alenaksu  Are you using mdDialog for date time picker ? If yes can I ask you, how you are able to open mdDialog over another one?

**Comment by alenaksu** [comment]
@alphazhe yes, looking into the Angular Material code, I've found an undocumented property for mdDialog. Its name is *skipHide* and if setted to true, the $mdDialog service will not close other dialogs.

**Comment by alphazhe** [comment]
@alenaksu Thanks a lot ... it saved my day :)
