### ISSUE TITLE
Cancel and OK label are not localizable

### ISSUE THREAD

**Issue by Soulcyber** [alenaksu/mdPickers#8]
Hi, maybe a new function to set these 2 label without go in the code and change them manually?
(and prevent us to update the labels everytime we update the picker javascript)

something like
```
$mdDatePicker.setNegativeBtnLabel('Back')
$mdDatePicker.setPositiveBtnLabel('Fine')
```

What do you think?

Thanks
Mat

**Comment by qihaiyan** [comment]
the function this.setOKButtonLabel is added,but how to use? when i call the function,the error is '$mdpDatePicker.setOKButtonLabel is not a function'.
i use it in es2016 javascript:
constructor($mdDialog, $scope, $resource, $mdpDatePicker) {
        'ngInject';
        $mdpDatePicker.setOKButtonLabel('ok');

**Comment by corentin-gautier** [comment]
@qihaiyan You have to use the provider

**Comment by BkSouX** [comment]
Hi @corentin-gautier , how to do that ?
Can't find the function when doing 

`$mdpDatePicker.setCancelButtonLabel('Just a text');`

TypeError: $mdpDatePicker.setCancelButtonLabel is not a function

Bruno

**Comment by corentin-gautier** [comment]
@BkSouX just like I said :) Use the provider : 

``` javascript
$mdpDatePickerProvider.setCancelButtonLabel('Annuler');
```

You have to do that in the config phase since it's a provider ;)

**Comment by BkSouX** [comment]
great thank you ;)
