### ISSUE TITLE
Datepicker not being cleared when model variable is unset

### ISSUE THREAD

**Issue by auronperalta** [alenaksu/mdPickers#84]
Hello! I used the following code in my view:

`<mdp-date-picker ng-model="ctrl.date"></mdp-date-picker>`

When I set ctrl.date to 'undefined', the datepicker kept the old date value on the input, but, when I accessed the variable, it had no value. I know the variable is being set to undefined correctly, but how do I reflect this change on the input? Do I have to use another way to reset the datepicker?

Thanks in advance!

**Comment by auronperalta** [comment]
I read this issue: https://github.com/alenaksu/mdPickers/issues/61 and, though it might be related, I'm not sure if it's the same problem.

**Comment by matheusJov** [comment]
I'm having the same problem :(

**Comment by matheusJov** [comment]
this solution solved my problem,
https://github.com/alenaksu/mdPickers/pull/75
thank you @benelliott
