### ISSUE TITLE
form valid problem

### ISSUE THREAD

**Issue by qihaiyan** [alenaksu/mdPickers#85]
when set the picker to required in a form,and  give the model a initial value in the controller,the picker will display the value, but the form is still invalid. here is a fork of your demo http://codepen.io/HaiYan/pen/ZWvNKy, and the valid is added to the "show picker" button. you can see the value is displayed but the button is still disabled.

**Comment by Marchrius** [comment]
@alenaksu are you working on this issue? I'm asking only to schedule a fix on my local branch.

**Comment by alenaksu** [comment]
@Marchrius I've assigned it to the next milestone, but I can't give you a date. I hope in some days I can find the time for fix all the issues and release a new version.

**Comment by AnirudhaGohokar** [comment]
@Marchrius  Thanks for the temporary fix though I think this is still not merged with the master branch..
For now have made a directive to temporarily fix the issue

```
            commonDirectiveModule.directive('mdpDatePickerRequiredFix', function () {
                return {
                    link: function (scope, element, attrs, ngModel) {
                        ngModel.$validators.required = function(modelValue, viewValue) {
                     return !(modelValue === undefined || modelValue == null || modelValue == '');
                };
                    },
                    require: 'ngModel',
                    restrict: 'A'
                };
            });
```

**Comment by mick050** [comment]
Trying to contact alenaksu regarding consulting work on the mdPickers.  If anyone knows how to get in touch with him, please ask him to e-Mail me at mcarlson@omniticket.com
