### ISSUE TITLE
<input> size shouldn't be automatically updated

### ISSUE THREAD

**Issue by thaod** [alenaksu/mdPickers#89]
The size of <input> tag in Datepicker/Timepicker controls are now updated after we change its value. That causes the length of control is shorten than the initial length. Especially when we clear value in the control.

- Initial length:
![mdp_initial](https://cloud.githubusercontent.com/assets/11632797/14712980/8de610b4-0809-11e6-8f1e-cff0048d4055.png)

- After pick date:
![mdp_with_value](https://cloud.githubusercontent.com/assets/11632797/14713006/aa1bd17e-0809-11e6-8d19-c0afbf095274.png)

- After clear value:
![mdp_clear](https://cloud.githubusercontent.com/assets/11632797/14713014/aebe29de-0809-11e6-8f0d-82bd7fa0ef76.png)

I think the length should be kept as initial state.

**Comment by thaod** [comment]
I also find that `flex` doesn't work with `mdp-datepicker`. When we add `flex`, `mdp-datepicker` width is expanded but the width of its `md-input-container` stays the same.

**Comment by thaod** [comment]
Btw if you don't mind, @alenaksu , can I try to work on this issue?

**Comment by rvarbanov** [comment]
@thaod you don't need to ask for permission to work on an issue and submit a PR 😄
