### ISSUE TITLE
mdp-datepicker inside mdDialog - Close button

### ISSUE THREAD

**Issue by tehabstract** [alenaksu/mdPickers#99]
I know that nesting mdDialog is not supported, but I tried it and it worked, only I had a problem with closing the mdp-datepicker, since the close button would close the first dialog opened. So I fixed with editing 132 line of code and giving it an confirm with no arguments. I leave up to you to think about adding it ... Anyways good work, starred! 

Edit: Just found out it resets my model, but nvm I'll still go with this :)
Edit 2: Okay, fixed it with currentDate as argument :)

```
this.cancel = function() {
    if (currentDate instanceof Date) {
        $mdDialog.hide(currentDate);
    } else {
        $mdDialog.hide(null);
    }
};
```

**Comment by alenaksu** [comment]
@tehabstract please take a look here and tell me if it helps
https://github.com/alenaksu/mdPickers/issues/72

**Comment by pabramowitsch** [comment]
Thanks for the fix tehabstract,  If you're already in a popup you'd probably also want to put 
`clickOutsideToClose : false,`     at around line 181 where the popup is defined.  
As set to `true` If you click outside the date dialog it will close the underlying dialog first.

**Comment by marchrius** [comment]
You can use `skipHide: true` on parent $mdDialog to skip the hide event and close manually.

Reference: [Angular Material Issue 7262](https://github.com/angular/material/issues/7262)

**Comment by alenaksu** [comment]
I close the issue. Feel free to reopen if you need support
